backend:
  name: git-gateway
  branch: netlify-cms

media_folder: static/img
public_folder: /img

collections:
  - name: 'support'
    label: 'Supports'
    folder: 'data/support'
    create: true
    slug: '{{slug}}'
    identifier_field: url
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Url', name: 'url', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
